package models



const (
	ROLLDICE = "ROLL_DICE"
	MOVEPOS = "MOVE_POS"
	BUYBLOCK = "BUY_BLOCK"
	ACTIONCARD = "ACTION_CARD"
	CHANGEPLAYER = "CHANGE_PLAYER"
	CALCULATERENT = "CALCULATE_RENT"
	BUYPROPERTY = "BUY_PROPERTY"
	PAYRENT = "PAY_RENT"
	SELLPROPERTY = "SELL_PROPERTY"
	RENT = "RENT"

	CITY = "CITY"
	UTILITY = "UTILITY"
	SPECIALCARD = "SPECIAL_CARD"

	COMMUNITYCHEST = "COMMUNITY_CHEST"
	CHANCE = "CHANCE"
	INCOMETAX = "INCOME_TAX"
	JAIL = "JAIL"
	FREEPARKING = "FREE_PARKING"
	GOTOJAIL = "GO_TO_JAIL"
	PROPERTYTAX = "PROPERTY_TAX"
	GOTOSTART = "GO_TO_START"
	JUMPTOMUMBAI = "JUMP_TO_MUMBAI"
	HOUSEHOTELFINE = "HOUSE_HOTEL_FINE"
	GETOUTOFJAIL = "GET_OUT_OF_JAIL_CARD"

	BLOCKED = "BLOCKED"
	SOLD = "SOLD"
	OWNED = "OWNED"

	HOUSEHOTEL = "HOUSE_HOTEL"
	BASE = "BASE"
	COLOUR = "COLOUR"
	HOUSE_1 = "HOUSE_1"
	HOUSE_2 = "HOUSE_2"
	HOUSE_3 = "HOUSE_3"
	HOUSE_4 = "HOUSE_4"
	HOTEL = "HOTEL"

)