package models



const (
	ROLLDICE = "ROLL_DICE"
	MOVEPOS = "MOVE_POS"
	BUYBLOCK = "BUY_BLOCK"
	ACTIONCARD = "ACTION_CARD"
	SELL = "SELL"
	RENT = "RENT"

	CITY = "CITY"
	UTILITY = "UTILITY"
	SPECIALCARD = "SPECIAL_CARD"
	COMMUNITYCHEST = "COMMUNITY_CHEST"

)